from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("8.10.0")

##### setup report #####
configfile: "config/config.yaml"

##### load rules #####
include: "rules/common.smk"
include: "rules/merge_fq.smk"
include: "rules/trimming.smk"
include: "rules/kallisto.smk"
include: "rules/quality_check.smk"




rule all:
    input:
        # Paired-end trimmed
        expand(
            resolve_results_filepath("reads", "trimmed/{sample}-R1.trimmed.fq.gz"),
            sample=SAMPLES_PE
        ),

        expand(
            resolve_results_filepath("reads", "trimmed/{sample}-R2.trimmed.fq.gz"),
            sample=SAMPLES_PE
        ),

        # Single-end trimmed (only if present)
        expand(
            resolve_results_filepath("reads", "trimmed/se/{sample}.trimmed.fq.gz"),
            sample=SAMPLES_SE
        ),

        # Kallisto quantification outputs
        expand(
            resolve_results_filepath("kallisto", "{sample}/abundance.h5"),
            sample=SAMPLES_PE
        ),
        expand(
            resolve_results_filepath("kallisto", "{sample}/abundance.tsv"),
            sample=SAMPLES_PE
        ),
        expand(
            resolve_results_filepath("kallisto", "{sample}/run_info.json"),
            sample=SAMPLES_PE
        ),

        expand(
            resolve_results_filepath("kallisto", "{sample}/se/abundance.se.h5"),
            sample=SAMPLES_SE
        ),
        expand(
            resolve_results_filepath("kallisto", "{sample}/se/abundance.se.tsv"),
            sample=SAMPLES_SE
        ),
        expand(
            resolve_results_filepath("kallisto", "{sample}/se/run_info.se.json"),
            sample=SAMPLES_SE),

        # fastqc PE
        expand(
            resolve_results_filepath("qc","fastqc/{sample}_R1_fastqc.zip"),
            sample=SAMPLES_PE
        ),
        expand(
            resolve_results_filepath("qc","fastqc/{sample}_R2_fastqc.zip"),
            sample=SAMPLES_PE
        ),

        # fastqc SE
        expand(
            resolve_results_filepath("qc","fastqc/se/{sample}_SE_fastqc.zip"),
            sample=SAMPLES_SE
        ),

        # multiqc final report
        resolve_results_filepath("qc","multiqc/multiqc_report.html")

       






