from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("8.10.0")

##### setup report #####
configfile: "config/config.yaml"

##### load rules #####
include: "rules/common.smk"
include: "rules/merge_fq.smk"
include: "rules/trimming.smk"
include: "rules/kallisto.smk"

# List of samples – already loaded in common.smk
SAMPLES = samples["sample"].tolist()

rule all:
    input:
        # Paired-end trimmed
        expand(resolve_results_filepath("reads","trimmed/{sample}-R1.trimmed.fq.gz"),sample=SAMPLES),
        expand(resolve_results_filepath("reads","trimmed/{sample}-R2.trimmed.fq.gz"),sample=SAMPLES),

        # Single-end trimmed (only if present)
        expand(resolve_results_filepath("reads","trimmed/{sample}.trimmed.fq.gz"),sample=SAMPLES),

        # Kallisto quantification outputs
        expand(resolve_results_filepath("kallisto","{sample}/abundance.h5"),sample=SAMPLES),
        expand(resolve_results_filepath("kallisto","{sample}/abundance.tsv"),sample=SAMPLES),
        expand(resolve_results_filepath("kallisto","{sample}/run_info.json"),sample=SAMPLES),



       






