name: ride
channels:
    - bioconda
    - conda-forge
    - anaconda
    - defaults
dependencies:
    - conda==24.7.1
    - python==3.12.7
    - drmaa==0.7.9
    - snakemake==8.24.1
    - snakemake-executor-plugin-drmaa==0.1.5

