samples: config/samples.tsv
units: config/units.tsv
reheader: config/reheader.tsv

paths:
  results_dir: "results"
  workdir: "."

resources:
    genome:
        basepath: "/path/to/refdata"
        provider: "ensembl"
        release: "GRCh38"
        fasta: "Homo_sapiens.GRCh38.dna.primary_assembly.fa"
        gtf: "Homo_sapiens.GRCh38.115.gtf"

    transcriptome:
        basepath: "/path/to/refdata"
        provider: "ensembl"
        release: "GRCh38"
        cdna: "Homo_sapiens.GRCh38.cdna.all.fa.gz"

    rseqc:
        basepath: "/path/to/refdata/rseqc"
        housekeeping: "hg38.HouseKeepingGenes.bed"
        refseq: "hg38_RefSeq.bed"

trimming:
  quality: 20
  min_length: 20
  trim_poly_g: true
  trim_poly_x: true
  detect_adapter: true

kallisto:
  index_name: "kallisto_index.idx"
  frag_len: 280
  frag_sd: 80
  boot: 100

star:
  index_dir: "index"
  sjdb_overhang: 100
  extra_params: "" # "--quantMode GeneCounts "